---
- name: Install Epel 
  yum:
    name: epel-release
    state: latest

- name: Install Java OpenJDK 8
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: Disable Selinux
  selinux:
    state: disabled
  register: selinux_status

- name: Install Jenkins repository 
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/

- name: Add a repository to the system
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  # shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install latest version of Jenkins
  yum:
    name: jenkins
    state: latest

- name: Start service jenkins
  service:
    name: jenkins
    state: started

- name: Enable service jenkins
  service:
    name: jenkins
    enabled: yes

- name: Install firewalld package
  yum:
    name: firewalld
    state: latest

- name: Start service firewalld
  service:
    name: firewalld
    state: started

- name: Enable service firewalld
  service:
    name: firewalld
    enabled: yes

- name: Opening port 80
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: ensure forwarding rule in firewalld
  firewalld:
    state: enabled
    rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080
    zone: public
    permanent: true
    immediate: true

- name: Opening port 22
  firewalld: 
    service: ssh
    permanent: true
    state: enabled